version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    environment:
      - NUXT_PUBLIC_GA_MEASURMENT_ID
      - NUXT_PUBLIC_RE_CAPTCHA_SITE_KEY
      - NUXT_MAIL_FROM
      - NUXT_MAIL_TO
      - NUXT_POSTMARK_SERVER_TOKEN
      - NUXT_RE_CAPTCHA_SECRET_KEY
    command: node .output/server/index.mjs
    ports: ["${APP_SERVICE_PORT:-3000}:3000"]
