docker/build:
	doppler run -- docker-compose build

docker/up:
	doppler run -- docker-compose up -d

docker/down:
	doppler run -- docker-compose down

docker/stop:
	pwd \
| xargs basename \
| xargs -I {} echo "-qf name=^{}.+$$" \
| xargs docker ps \
| xargs -L1 docker stop
